
package br.com.nextage.rmaweb.ws.rhweb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RmawebWs", targetNamespace = "http://ws.rhweb_ws.nextage.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RmawebWs {


    /**
     * 
     * @param filtroImportacaoBloco
     * @return
     *     returns java.util.List<br.com.nextage.rmaweb.ws.rhweb.Pessoa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPessoasRmaweb", targetNamespace = "http://ws.rhweb_ws.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.rhweb.ListarPessoasRmaweb")
    @ResponseWrapper(localName = "listarPessoasRmawebResponse", targetNamespace = "http://ws.rhweb_ws.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.rhweb.ListarPessoasRmawebResponse")
    @Action(input = "http://ws.rhweb_ws.nextage.com.br/RmawebWs/listarPessoasRmawebRequest", output = "http://ws.rhweb_ws.nextage.com.br/RmawebWs/listarPessoasRmawebResponse")
    public List<Pessoa> listarPessoasRmaweb(
        @WebParam(name = "filtroImportacaoBloco", targetNamespace = "")
        FiltroImportacaoBloco filtroImportacaoBloco);

}
