
package br.com.nextage.rmaweb.ws.rhweb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RmawebWs", targetNamespace = "http://ws.rhweb_ws.nextage.com.br/", wsdlLocation = "http://10.50.1.55:8084/rhweb-ws_ccsl/RmawebWs?wsdl")
public class RmawebWs_Service
    extends Service
{

    private final static URL RMAWEBWS_WSDL_LOCATION;
    private final static WebServiceException RMAWEBWS_EXCEPTION;
    private final static QName RMAWEBWS_QNAME = new QName("http://ws.rhweb_ws.nextage.com.br/", "RmawebWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.1.55:8084/rhweb-ws_ccsl/RmawebWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RMAWEBWS_WSDL_LOCATION = url;
        RMAWEBWS_EXCEPTION = e;
    }

    public RmawebWs_Service() {
        super(__getWsdlLocation(), RMAWEBWS_QNAME);
    }

    public RmawebWs_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RMAWEBWS_QNAME, features);
    }

    public RmawebWs_Service(URL wsdlLocation) {
        super(wsdlLocation, RMAWEBWS_QNAME);
    }

    public RmawebWs_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RMAWEBWS_QNAME, features);
    }

    public RmawebWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RmawebWs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RmawebWs
     */
    @WebEndpoint(name = "RmawebWsPort")
    public RmawebWs getRmawebWsPort() {
        return super.getPort(new QName("http://ws.rhweb_ws.nextage.com.br/", "RmawebWsPort"), RmawebWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RmawebWs
     */
    @WebEndpoint(name = "RmawebWsPort")
    public RmawebWs getRmawebWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.rhweb_ws.nextage.com.br/", "RmawebWsPort"), RmawebWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RMAWEBWS_EXCEPTION!= null) {
            throw RMAWEBWS_EXCEPTION;
        }
        return RMAWEBWS_WSDL_LOCATION;
    }

}
