INSERT INTO TB_STATUS (ID,CODIGO,NOME) VALUES 
(1,'Cad','Cadastrada')
,(2,'Env','Enviar Aprovação')
,(3,'AprGa','Aprovação Gerente Área')
,(4,'AprGc','Aprovação Custos')
,(5,'CompCust','Complemento Informações de Custos')
,(6,'Rep','Reprovada')
,(7,'Can','Cancelada')
,(8,'AprGo','Aprovação Gerente Obra')
,(9,'AgEst','Em Validação Estoque')
,(10,'AgComp','Aguardando Compra')
,(11,'AgRet','Aguardando Retirada')
,(12,'RecEst','Recusado Estoquista')
,(13,'MatComAgRec','Aguardando Recebimento')
,(14,'RetParc','Retirado')
,(15,'Fim','Finalizado')
,(16,'RecParc','Recebido Parcialmente')
,(18,'Rec','Recebido')
,(19,'AprCo','Aprovação Coordenador')
,(20,'SolicTransf','Transferência solicitada')
,(21,'Indisp','Indisponível')
,(25,'AprRre','Aprovação Responsável Retirada Estoque')
,(26,'MatAlt','Material Alterado')
,(27,'MatEstornoRec','Estornado')
;