




CREATE VIEW [dbo].[VW_DOCUMENTO_RESPONSABILIDADE]
AS
SELECT     ROW_NUMBER() OVER (ORDER BY RMMS.ID) AS ID, RMMS.ID AS RM_MATERIAL_STATUS_ID, RMMS.OBSERVACAO AS OBSERVACAO, 
RMM.RM_MATERIAL_ID AS RM_MATERIAL_ID, RMM.FLUXO_MATERIAL AS FLUXO_MATERIAL, RMM.CF_RESPONSAVEL AS CF_RESPONSAVEL, 
RESPONSAVEL.NOME AS NOME_RESPONSAVEL, RESPONSAVEL.REFERENCIA AS REFERENCIA_RESPONSAVEL, RESPONSAVEL.PESSOA_ID AS RESPONSAVEL_PESSOA_ID, RMM.QUANTIDADE AS QUANTIDADE, 
RMM.DOCUMENTO_RESPONSAVEL_IMPRESSO AS DOCUMENTO_RESPONSAVEL_IMPRESSO, RMM.PROTOCOLO_RESPONSABILIDADE AS PROTOCOLO_RESPONSABILIDADE, 
RMM.PREFIXO_EQUIPAMENTO AS PREFIXO_EQUIPAMENTO, DEP.DEPOSITO_ID AS DEPOSITO_ID, DEP.NOME AS DEPOSITO_NOME, DEP.CODIGO AS DEPOSITO_CODIGO, 
RM.RM_ID AS RM_ID, RM.NUMERO_RM AS NUMERO_RM, RM.DATA_EMISSAO AS DATA_EMISSAO, RM.DATA_APLICACAO AS DATA_APLICACAO, 
M.MATERIAL_ID AS MATERIAL_ID, M.CODIGO AS MATERIAL_CODIGO, M.NOME AS MATERIAL_NOME, M.PATRIMONIADO AS MATERIAL_PATRIMONIADO, 
M.HIERARQUIA AS MATERIAL_HIERARQUIA, UM.SIGLA AS UNIDADE_MEDIDA_SIGLA, UM.DESCRICAO AS UNIDADE_MEDIDA_DESCRICAO, UM.UNIDADE_MEDIDA_ID AS UNIDADE_MEDIDA_ID,
TM.TIPO_MATERIAL_ID AS TIPO_MATERIAL_ID, TM.CODIGO AS TIPO_MATERIAL_CODIGO, TM.DESCRICAO AS TIPO_MATERIAL_DESCRICAO, S.CODIGO AS STATUS_CODIGO, S.NOME AS STATUS_NOME, 
USUARIO.PESSOA_ID AS USUARIO_ID, USUARIO.NOME AS USUARIO_NOME, USUARIO.REFERENCIA AS USUARIO_REFERENCIA, 
REQUISITANTE.PESSOA_ID AS REQUISITANTE_ID, REQUISITANTE.NOME AS REQUISITANTE_NOME, REQUISITANTE.REFERENCIA AS REQUISITANTE_REFERENCIA, 
REQUISITANTE.FUNCAO AS REQUISITANTE_FUNCAO, TR.CODIGO AS TIPO_REQUISICAO_CODIGO, SE.DESCRICAO AS REQUISITANTE_SETOR,
EAP.ID AS RM_EAP_MULTI_EMPRESA_ID,
EAP_DEP.ID AS DEPOSITO_EAP_MULTI_EMPRESA_ID,
EAP.DESCRICAO AS RM_EAP_MULTI_EMPRESA_DESCRICAO,
EAP_DEP.DESCRICAO AS DEPOSITO_EAP_MULTI_EMPRESA_DESCRICAO,
    (SELECT     DATEDIFF(DAY, GETDATE(), RMM.DATA_PREVISAO_CHEGADA)) AS DIAS_PREVISTOS, data_status.DATA_APROV_GERENTE_AREA, 
data_status.DATA_APROV_GERENTE_CUSTOS, data_status.DATA_APROV_COORDENADOR, data_status.DATA_APROV_RESPONSAVEL_RETIRADA_ESTOQUE, 
data_status.DATA_APROV_COMPLEMENTO_CUSTOS,
    (SELECT     CASE WHEN EXISTS
                                 (SELECT     RMR.RM_MATERIAL_RETIRADA_ID
                                   FROM          TB_RM_MATERIAL_RETIRADA RMR
                                   WHERE      RMM.RM_MATERIAL_ID = RMR.RM_MATERIAL_ID AND RMR.PRE_RETIRADA = 0 AND RMR.DATA_AUTENTICACAO IS NULL) AND 
                             (RMM.CONFIRMA_RET_NAO_PRESENCIAL IS NULL OR
                             RMM.CONFIRMA_RET_NAO_PRESENCIAL = 0) AND EXISTS
                                 (SELECT     RMS.ID
                                   FROM          TB_RM_MATERIAL_STATUS RMS LEFT JOIN
                                                          TB_STATUS S ON RMS.STATUS_ID = S.ID
                                   WHERE      RMS.RM_MATERIAL_ID = RMM.RM_MATERIAL_ID AND (RMS.IS_HISTORICO IS NULL OR
                                                          RMS.IS_HISTORICO = 0) AND S.CODIGO = 'Fim') THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END) AS CONFIRMAR_RETIRADA,
    (SELECT     sum([QUANTIDADE])
      FROM          [TB_RM_MATERIAL_RECEBIMENTO] AS rec
      WHERE      rec.[RM_MATERIAL_ID] = RMM.[RM_MATERIAL_ID]) AS QTDE_RECEBIDA
FROM         TB_RM_MATERIAL_STATUS RMMS LEFT JOIN
                      TB_RM_MATERIAL RMM ON RMM.RM_MATERIAL_ID = RMMS.RM_MATERIAL_ID LEFT JOIN
                      TB_RM RM ON RM.RM_ID = RMM.RM_ID LEFT JOIN
                      TB_MATERIAL M ON M.MATERIAL_ID = RMM.MATERIAL_ID LEFT JOIN
                      TB_UNIDADE_MEDIDA UM ON M.UNIDADE_MEDIDA_ID = UM.UNIDADE_MEDIDA_ID LEFT JOIN
                      TB_STATUS S ON S.ID = RMMS.STATUS_ID LEFT JOIN
                      TB_USUARIO U ON U.USUARIO_ID = RM.USUARIO_ID LEFT JOIN
                      TB_PESSOA USUARIO ON USUARIO.PESSOA_ID = U.PESSOA_ID LEFT JOIN
         TB_PESSOA REQUISITANTE ON REQUISITANTE.PESSOA_ID = RM.REQUISITANTE_ID LEFT JOIN
                      TB_PESSOA RESPONSAVEL ON RESPONSAVEL.PESSOA_ID = RMM.PESSOA_RESPONSAVEL_ID LEFT JOIN
                      TB_TIPO_REQUISICAO TR ON TR.TIPO_REQUISICAO_ID = RM.TIPO_REQUISICAO_ID LEFT JOIN
                      TB_TIPO_MATERIAL TM ON TM.TIPO_MATERIAL_ID = M.TIPO_MATERIAL_ID LEFT JOIN
                      TB_SETOR SE ON SE.SETOR_ID = REQUISITANTE.SETOR_ID LEFT JOIN
                      TB_DEPOSITO DEP ON RMM.DEPOSITO_ID = DEP.DEPOSITO_ID LEFT JOIN
					  TB_EAP_MULTI_EMPRESA EAP ON EAP.ID = RM.EAP_MULTI_EMPRESA_ID LEFT JOIN
					  TB_EAP_MULTI_EMPRESA EAP_DEP ON EAP_DEP.ID = DEP.EAP_MULTI_EMPRESA_ID LEFT JOIN

                          (SELECT     [3] AS DATA_APROV_GERENTE_AREA, [4] AS DATA_APROV_GERENTE_CUSTOS, [19] AS DATA_APROV_COORDENADOR, 
                                                   [25] AS DATA_APROV_RESPONSAVEL_RETIRADA_ESTOQUE, [5] AS DATA_APROV_COMPLEMENTO_CUSTOS, RM_MATERIAL_ID
                            FROM          (SELECT     RMS2.RM_MATERIAL_ID, RMS2.STATUS_ID, RMS2.DATA_HORA_STATUS
                                                    FROM          TB_RM_MATERIAL_STATUS RMS2
                                                    WHERE      RMS2.STATUS_ID IN (3, 4, 19, 25, 5)) C PIVOT (MAX(DATA_HORA_STATUS) FOR STATUS_ID IN ([3], [4], [19], [25], [5])) AS P) AS data_status ON 
                      data_status.RM_MATERIAL_ID = RMM.RM_MATERIAL_ID
WHERE     RMMS.ID IN
                          (SELECT     MAX(ID)
                            FROM          TB_RM_MATERIAL_STATUS
                            WHERE      RM_MATERIAL_ID = RMM.RM_MATERIAL_ID)





