
CREATE VIEW [dbo].[VW_MATERIAL_DEPOSITO_SAIDA_RESERVA]
AS
SELECT     ROW_NUMBER() OVER (ORDER BY ID) AS ID, MR.ID AS MATERIAL_DEPOSITO_SAIDA_RESERVA_ID,
    (SELECT     TOP (1) ID
      FROM          TB_RM_MATERIAL_STATUS RMS
      WHERE      RMS.RM_MATERIAL_ID = MR.RM_MATERIAL AND (RMS.IS_HISTORICO IS NULL OR
                             RMS.IS_HISTORICO = 0)
      ORDER BY ID DESC) AS RM_MATERIAL_STATUS_ID,
    (SELECT     TOP (1) P.PESSOA_ID
      FROM          TB_PESSOA P LEFT JOIN
                             TB_RM_MATERIAL RMMATERIAL ON RMMATERIAL.RM_MATERIAL_ID = MR.RM_MATERIAL
      WHERE      P.REFERENCIA = RMMATERIAL.CF_RESPONSAVEL) AS PESSOA_ID
FROM         TB_MATERIAL_DEPOSITO_SAIDA_RESERVA MR

