
package br.com.nextage.rmaweb.ws.cpweb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SincEstoque", targetNamespace = "http://ws.cpweb.nextage.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SincEstoque {


    /**
     * 
     * @param filtro
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCpNaoPatrimoniados", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.ListarCpNaoPatrimoniados")
    @ResponseWrapper(localName = "listarCpNaoPatrimoniadosResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.ListarCpNaoPatrimoniadosResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/listarCpNaoPatrimoniadosRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/listarCpNaoPatrimoniadosResponse")
    Double listarCpNaoPatrimoniados(
            @WebParam(name = "filtro", targetNamespace = "")
            FiltroEquipamentoEstoqueVo filtro);

    /**
     * 
     * @param sincEquipamentoVo
     * @return
     *     returns br.com.nextage.rmaweb.ws.cpweb.Info
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enviaReserva", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.EnviaReserva")
    @ResponseWrapper(localName = "enviaReservaResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.EnviaReservaResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/enviaReservaRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/enviaReservaResponse")
    Info enviaReserva(
            @WebParam(name = "sincEquipamentoVo", targetNamespace = "")
            SincEquipamentoVo sincEquipamentoVo);

    /**
     *
     * @param sincTransferenciaVo
     * @return
     *     returns br.com.nextage.rmaweb.ws.cpweb.Info
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferir", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.Transferir")
    @ResponseWrapper(localName = "transferirResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.TransferirResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/transferirRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/transferirResponse")
    Info transferir(
            @WebParam(name = "sincTransferenciaVo", targetNamespace = "")
            SincTransferenciaVo sincTransferenciaVo);

    /**
     *
     * @param listaEquipamento
     * @return
     *     returns br.com.nextage.rmaweb.ws.cpweb.Info
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gerarCautela", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.GerarCautela")
    @ResponseWrapper(localName = "gerarCautelaResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.GerarCautelaResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/gerarCautelaRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/gerarCautelaResponse")
    Info gerarCautela(
            @WebParam(name = "listaEquipamento", targetNamespace = "")
            List<SincEquipamentoVo> listaEquipamento);

    /**
     * 
     * @param filtro
     * @return
     *     returns java.util.List<br.com.nextage.rmaweb.ws.cpweb.EquipamentoEstoque>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEstoque", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.ListarEstoque")
    @ResponseWrapper(localName = "listarEstoqueResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.ListarEstoqueResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/listarEstoqueRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/listarEstoqueResponse")
    List<EquipamentoEstoque> listarEstoque(
            @WebParam(name = "filtro", targetNamespace = "")
            FiltroEquipamentoEstoqueVo filtro);

    /**
     * 
     * @param sincEquipamentoVo
     * @return
     *     returns br.com.nextage.rmaweb.ws.cpweb.Info
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enviaEquipamento", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.EnviaEquipamento")
    @ResponseWrapper(localName = "enviaEquipamentoResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.EnviaEquipamentoResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/enviaEquipamentoRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/enviaEquipamentoResponse")
    Info enviaEquipamento(
            @WebParam(name = "sincEquipamentoVo", targetNamespace = "")
            SincEquipamentoVo sincEquipamentoVo);

    /**
     *
     * @param prefixoEquipamentoVo
     * @return
     *     returns br.com.nextage.rmaweb.ws.cpweb.Info
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPatrimonio", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.ListarPatrimonio")
    @ResponseWrapper(localName = "listarPatrimonioResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.ListarPatrimonioResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/listarPatrimonioRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/listarPatrimonioResponse")
    Info listarPatrimonio(
            @WebParam(name = "prefixoEquipamentoVo", targetNamespace = "")
            PrefixoEquipamentoVo prefixoEquipamentoVo);

    /**
     *
     * @param filtro
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCpPatrimoniados", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.ListarCpPatrimoniados")
    @ResponseWrapper(localName = "listarCpPatrimoniadosResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.ListarCpPatrimoniadosResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/listarCpPatrimoniadosRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/listarCpPatrimoniadosResponse")
    Double listarCpPatrimoniados(
            @WebParam(name = "filtro", targetNamespace = "")
            FiltroEquipamentoEstoqueVo filtro);

    /**
     * 
     * @param filtro
     * @return
     *     returns br.com.nextage.rmaweb.ws.cpweb.Info
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "estornarEstoque", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.EstornarEstoque")
    @ResponseWrapper(localName = "estornarEstoqueResponse", targetNamespace = "http://ws.cpweb.nextage.com.br/", className = "br.com.nextage.rmaweb.ws.cpweb.EstornarEstoqueResponse")
    @Action(input = "http://ws.cpweb.nextage.com.br/SincEstoque/estornarEstoqueRequest", output = "http://ws.cpweb.nextage.com.br/SincEstoque/estornarEstoqueResponse")
    Info estornarEstoque(
            @WebParam(name = "filtro", targetNamespace = "")
            SincEquipamentoVo filtro);

}
