
package br.com.nextage.rmaweb.ws.sap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BS_RMAWEB_SI_SolicitaReservaSyncOut_x_x", targetNamespace = "urn:cccc.rmaweb.reservamat", wsdlLocation = "file:/D:/workspace_intellij/rmaweb/rmaweb/src/wsdl/sepd.camargocorrea.com.br/dir/wsdl.p_sa/e43c85c7abf73975991abdeb9c602985.wsdl")
public class BSRMAWEBSISolicitaReservaSyncOutXX
    extends Service
{

    private final static URL BSRMAWEBSISOLICITARESERVASYNCOUTXX_WSDL_LOCATION;
    private final static WebServiceException BSRMAWEBSISOLICITARESERVASYNCOUTXX_EXCEPTION;
    private final static QName BSRMAWEBSISOLICITARESERVASYNCOUTXX_QNAME = new QName("urn:cccc.rmaweb.reservamat", "BS_RMAWEB_SI_SolicitaReservaSyncOut_x_x");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace_intellij/rmaweb/rmaweb/src/wsdl/sepd.camargocorrea.com.br/dir/wsdl.p_sa/e43c85c7abf73975991abdeb9c602985.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSRMAWEBSISOLICITARESERVASYNCOUTXX_WSDL_LOCATION = url;
        BSRMAWEBSISOLICITARESERVASYNCOUTXX_EXCEPTION = e;
    }

    public BSRMAWEBSISolicitaReservaSyncOutXX() {
        super(__getWsdlLocation(), BSRMAWEBSISOLICITARESERVASYNCOUTXX_QNAME);
    }

    public BSRMAWEBSISolicitaReservaSyncOutXX(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSRMAWEBSISOLICITARESERVASYNCOUTXX_QNAME, features);
    }

    public BSRMAWEBSISolicitaReservaSyncOutXX(URL wsdlLocation) {
        super(wsdlLocation, BSRMAWEBSISOLICITARESERVASYNCOUTXX_QNAME);
    }

    public BSRMAWEBSISolicitaReservaSyncOutXX(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSRMAWEBSISOLICITARESERVASYNCOUTXX_QNAME, features);
    }

    public BSRMAWEBSISolicitaReservaSyncOutXX(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSRMAWEBSISolicitaReservaSyncOutXX(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SISolicitaReservaSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISolicitaReservaSyncOut getHTTPPort() {
        return super.getPort(new QName("urn:cccc.rmaweb.reservamat", "HTTP_Port"), SISolicitaReservaSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISolicitaReservaSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISolicitaReservaSyncOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cccc.rmaweb.reservamat", "HTTP_Port"), SISolicitaReservaSyncOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SISolicitaReservaSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISolicitaReservaSyncOut getHTTPSPort() {
        return super.getPort(new QName("urn:cccc.rmaweb.reservamat", "HTTPS_Port"), SISolicitaReservaSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISolicitaReservaSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISolicitaReservaSyncOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cccc.rmaweb.reservamat", "HTTPS_Port"), SISolicitaReservaSyncOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSRMAWEBSISOLICITARESERVASYNCOUTXX_EXCEPTION!= null) {
            throw BSRMAWEBSISOLICITARESERVASYNCOUTXX_EXCEPTION;
        }
        return BSRMAWEBSISOLICITARESERVASYNCOUTXX_WSDL_LOCATION;
    }

}
