
package br.com.nextage.rmaweb.ws.sap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BS_RMAWEB_SI_CriaSaidaSyncOut_x_x", targetNamespace = "urn:cccc.rmaweb.saidamercadoria", wsdlLocation = "file:/D:/workspace_intellij/rmaweb/rmaweb/src/wsdl/sepd.camargocorrea.com.br/dir/wsdl.p_sa/ba50777f2d28382999616e90cb32b3ee.wsdl")
public class BSRMAWEBSICriaSaidaSyncOutXX
    extends Service
{

    private final static URL BSRMAWEBSICRIASAIDASYNCOUTXX_WSDL_LOCATION;
    private final static WebServiceException BSRMAWEBSICRIASAIDASYNCOUTXX_EXCEPTION;
    private final static QName BSRMAWEBSICRIASAIDASYNCOUTXX_QNAME = new QName("urn:cccc.rmaweb.saidamercadoria", "BS_RMAWEB_SI_CriaSaidaSyncOut_x_x");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace_intellij/rmaweb/rmaweb/src/wsdl/sepd.camargocorrea.com.br/dir/wsdl.p_sa/ba50777f2d28382999616e90cb32b3ee.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSRMAWEBSICRIASAIDASYNCOUTXX_WSDL_LOCATION = url;
        BSRMAWEBSICRIASAIDASYNCOUTXX_EXCEPTION = e;
    }

    public BSRMAWEBSICriaSaidaSyncOutXX() {
        super(__getWsdlLocation(), BSRMAWEBSICRIASAIDASYNCOUTXX_QNAME);
    }

    public BSRMAWEBSICriaSaidaSyncOutXX(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSRMAWEBSICRIASAIDASYNCOUTXX_QNAME, features);
    }

    public BSRMAWEBSICriaSaidaSyncOutXX(URL wsdlLocation) {
        super(wsdlLocation, BSRMAWEBSICRIASAIDASYNCOUTXX_QNAME);
    }

    public BSRMAWEBSICriaSaidaSyncOutXX(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSRMAWEBSICRIASAIDASYNCOUTXX_QNAME, features);
    }

    public BSRMAWEBSICriaSaidaSyncOutXX(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSRMAWEBSICriaSaidaSyncOutXX(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SICriaSaidaSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICriaSaidaSyncOut getHTTPPort() {
        return super.getPort(new QName("urn:cccc.rmaweb.saidamercadoria", "HTTP_Port"), SICriaSaidaSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICriaSaidaSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICriaSaidaSyncOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cccc.rmaweb.saidamercadoria", "HTTP_Port"), SICriaSaidaSyncOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SICriaSaidaSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICriaSaidaSyncOut getHTTPSPort() {
        return super.getPort(new QName("urn:cccc.rmaweb.saidamercadoria", "HTTPS_Port"), SICriaSaidaSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICriaSaidaSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICriaSaidaSyncOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cccc.rmaweb.saidamercadoria", "HTTPS_Port"), SICriaSaidaSyncOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSRMAWEBSICRIASAIDASYNCOUTXX_EXCEPTION!= null) {
            throw BSRMAWEBSICRIASAIDASYNCOUTXX_EXCEPTION;
        }
        return BSRMAWEBSICRIASAIDASYNCOUTXX_WSDL_LOCATION;
    }

}
