
package br.com.nextage.rmaweb.ws.sap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BS_RMAWEB_SI_SolicitaRequisicaoSyncOut_x_x", targetNamespace = "urn:cccc.rmaweb.requisicao", wsdlLocation = "file:/D:/workspace_intellij/rmaweb/rmaweb/src/wsdl/sepd.camargocorrea.com.br/dir/wsdl.p_sa/08f70cf76f0c3fa99dbccb34bb5a979f.wsdl")
public class BSRMAWEBSISolicitaRequisicaoSyncOutXX
    extends Service
{

    private final static URL BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_WSDL_LOCATION;
    private final static WebServiceException BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_EXCEPTION;
    private final static QName BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_QNAME = new QName("urn:cccc.rmaweb.requisicao", "BS_RMAWEB_SI_SolicitaRequisicaoSyncOut_x_x");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace_intellij/rmaweb/rmaweb/src/wsdl/sepd.camargocorrea.com.br/dir/wsdl.p_sa/08f70cf76f0c3fa99dbccb34bb5a979f.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_WSDL_LOCATION = url;
        BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_EXCEPTION = e;
    }

    public BSRMAWEBSISolicitaRequisicaoSyncOutXX() {
        super(__getWsdlLocation(), BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_QNAME);
    }

    public BSRMAWEBSISolicitaRequisicaoSyncOutXX(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_QNAME, features);
    }

    public BSRMAWEBSISolicitaRequisicaoSyncOutXX(URL wsdlLocation) {
        super(wsdlLocation, BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_QNAME);
    }

    public BSRMAWEBSISolicitaRequisicaoSyncOutXX(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_QNAME, features);
    }

    public BSRMAWEBSISolicitaRequisicaoSyncOutXX(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSRMAWEBSISolicitaRequisicaoSyncOutXX(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SISolicitaRequisicaoSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISolicitaRequisicaoSyncOut getHTTPPort() {
        return super.getPort(new QName("urn:cccc.rmaweb.requisicao", "HTTP_Port"), SISolicitaRequisicaoSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISolicitaRequisicaoSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISolicitaRequisicaoSyncOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cccc.rmaweb.requisicao", "HTTP_Port"), SISolicitaRequisicaoSyncOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SISolicitaRequisicaoSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISolicitaRequisicaoSyncOut getHTTPSPort() {
        return super.getPort(new QName("urn:cccc.rmaweb.requisicao", "HTTPS_Port"), SISolicitaRequisicaoSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISolicitaRequisicaoSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISolicitaRequisicaoSyncOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cccc.rmaweb.requisicao", "HTTPS_Port"), SISolicitaRequisicaoSyncOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_EXCEPTION!= null) {
            throw BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_EXCEPTION;
        }
        return BSRMAWEBSISOLICITAREQUISICAOSYNCOUTXX_WSDL_LOCATION;
    }

}
