
package br.com.nextage.rmaweb.ws.sap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_CriaSaidaSyncOut", targetNamespace = "urn:cccc.rmaweb.saidamercadoria")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SICriaSaidaSyncOut {


    /**
     * 
     * @param mtSolicitaSaida
     * @return
     *     returns br.com.nextage.rmaweb.ws.sap.DTSolicitaSaidaResponse
     * @throws P3MTErro
     */
    @WebMethod(operationName = "SI_CriaSaidaSyncOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SolicitaSaida_response", targetNamespace = "urn:cccc.rmaweb.saidamercadoria", partName = "MT_SolicitaSaida_response")
    public DTSolicitaSaidaResponse siCriaSaidaSyncOut(
        @WebParam(name = "MT_SolicitaSaida", targetNamespace = "urn:cccc.rmaweb.saidamercadoria", partName = "MT_SolicitaSaida")
        DTSolicitaSaida mtSolicitaSaida)
        throws P3MTErro
    ;

}
