
package br.com.nextage.rmaweb.ws.sap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_SolicitaReservaSyncOut", targetNamespace = "urn:cccc.rmaweb.reservamat")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SISolicitaReservaSyncOut {


    /**
     * 
     * @param mtSolicitaReserva
     * @return
     *     returns br.com.nextage.rmaweb.ws.sap.DTSolicitaReservaResponse
     * @throws P3MTErro
     */
    @WebMethod(operationName = "SI_SolicitaReservaSyncOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SolicitaReserva_response", targetNamespace = "urn:cccc.rmaweb.reservamat", partName = "MT_SolicitaReserva_response")
    public DTSolicitaReservaResponse siSolicitaReservaSyncOut(
        @WebParam(name = "MT_SolicitaReserva", targetNamespace = "urn:cccc.rmaweb.reservamat", partName = "MT_SolicitaReserva")
        DTSolicitaReserva mtSolicitaReserva)
        throws P3MTErro
    ;

}
