
package br.com.nextage.rmaweb.service.impl;

import com.sap.document.sap.rfc.functions.ZGLRMAWEB;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "service", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/home/adriano/projects/api/rmonline-ag-api-v1/src/main/java/zgl_rmaweb.xml")
public class ServiceSapAg
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/adriano/projects/api/rmonline-ag-api-v1/src/main/java/zgl_rmaweb.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public ServiceSapAg() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public ServiceSapAg(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public ServiceSapAg(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public ServiceSapAg(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public ServiceSapAg(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceSapAg(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZGLRMAWEB
     */
    @WebEndpoint(name = "binding")
    public ZGLRMAWEB getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZGLRMAWEB.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZGLRMAWEB
     */
    @WebEndpoint(name = "binding")
    public ZGLRMAWEB getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZGLRMAWEB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
