
package br.com.nextage.rmaweb.ws.sap.consultarEstoque;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BS_RMAWEB_SI_ConsultaEstoqueSyncOut_x_x", targetNamespace = "urn:cccc.rmaweb.consultaestoque", wsdlLocation = "file:/D:/workspace_intellij/rmaweb/rmaweb/src/wsdl/sepd.camargocorrea.com.br/dir/wsdl.p_sa/93058bb0621330e0ad2252b057367721.wsdl")
public class BSRMAWEBSIConsultaEstoqueSyncOutXX
    extends Service
{

    private final static URL BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_WSDL_LOCATION;
    private final static WebServiceException BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_EXCEPTION;
    private final static QName BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_QNAME = new QName("urn:cccc.rmaweb.consultaestoque", "BS_RMAWEB_SI_ConsultaEstoqueSyncOut_x_x");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace_intellij/rmaweb/rmaweb/src/wsdl/sepd.camargocorrea.com.br/dir/wsdl.p_sa/93058bb0621330e0ad2252b057367721.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_WSDL_LOCATION = url;
        BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_EXCEPTION = e;
    }

    public BSRMAWEBSIConsultaEstoqueSyncOutXX() {
        super(__getWsdlLocation(), BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_QNAME);
    }

    public BSRMAWEBSIConsultaEstoqueSyncOutXX(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_QNAME, features);
    }

    public BSRMAWEBSIConsultaEstoqueSyncOutXX(URL wsdlLocation) {
        super(wsdlLocation, BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_QNAME);
    }

    public BSRMAWEBSIConsultaEstoqueSyncOutXX(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_QNAME, features);
    }

    public BSRMAWEBSIConsultaEstoqueSyncOutXX(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSRMAWEBSIConsultaEstoqueSyncOutXX(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIConsultaEstoqueSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIConsultaEstoqueSyncOut getHTTPPort() {
        return super.getPort(new QName("urn:cccc.rmaweb.consultaestoque", "HTTP_Port"), SIConsultaEstoqueSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIConsultaEstoqueSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIConsultaEstoqueSyncOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cccc.rmaweb.consultaestoque", "HTTP_Port"), SIConsultaEstoqueSyncOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIConsultaEstoqueSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIConsultaEstoqueSyncOut getHTTPSPort() {
        return super.getPort(new QName("urn:cccc.rmaweb.consultaestoque", "HTTPS_Port"), SIConsultaEstoqueSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIConsultaEstoqueSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIConsultaEstoqueSyncOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:cccc.rmaweb.consultaestoque", "HTTPS_Port"), SIConsultaEstoqueSyncOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_EXCEPTION!= null) {
            throw BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_EXCEPTION;
        }
        return BSRMAWEBSICONSULTAESTOQUESYNCOUTXX_WSDL_LOCATION;
    }

}
