
package br.com.nextage.rmaweb.ws.sap.consultarEstoque;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ConsultaEstoqueSyncOut", targetNamespace = "urn:cccc.rmaweb.consultaestoque")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIConsultaEstoqueSyncOut {


    /**
     * 
     * @param mtConsultaEstoque
     * @return
     *     returns br.com.nextage.rmaweb.ws.sap.consultarEstoque.DTConsultaEstoqueResponse
     * @throws P3MTErro
     */
    @WebMethod(operationName = "SI_ConsultaEstoqueSyncOut", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ConsultaEstoque_Response", targetNamespace = "urn:cccc.rmaweb.consultaestoque", partName = "MT_ConsultaEstoque_Response")
    public DTConsultaEstoqueResponse siConsultaEstoqueSyncOut(
        @WebParam(name = "MT_ConsultaEstoque", targetNamespace = "urn:cccc.rmaweb.consultaestoque", partName = "MT_ConsultaEstoque")
        DTConsultaEstoque mtConsultaEstoque)
        throws P3MTErro
    ;

}
