
package com.sap.document.sap.rfc.functions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZGL_RMAWEB", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZGLRMAWEB {


    /**
     * 
     * @param tANEXO
     * @param tITENS
     * @return
     *     returns com.sap.document.sap.rfc.functions.ZGLSTABRMAREQRETURN
     */
    @WebMethod(operationName = "ZGL_RMA_CRIA_REQUISICAO", action = "urn:sap-com:document:sap:rfc:functions:ZGL_RMAWEB:ZGL_RMA_CRIA_REQUISICAORequest")
    @WebResult(name = "T_RETURN", targetNamespace = "")
    @RequestWrapper(localName = "ZGL_RMA_CRIA_REQUISICAO", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZGLRMACRIAREQUISICAO")
    @ResponseWrapper(localName = "ZGL_RMA_CRIA_REQUISICAOResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZGLRMACRIAREQUISICAOResponse")
    public ZGLSTABRMAREQRETURN zglRMACRIAREQUISICAO(
        @WebParam(name = "T_ITENS", targetNamespace = "")
        ZGLSTABRMAREQUISICAO tITENS,
        @WebParam(name = "T_ANEXO", targetNamespace = "")
        ZGLSTABRMAREQUISICAOANEXO tANEXO);

    /**
     * 
     * @param tITENS
     * @return
     *     returns com.sap.document.sap.rfc.functions.ZGLSTABRESRETURN
     */
    @WebMethod(operationName = "ZGL_RMA_CRIA_RESERVA", action = "urn:sap-com:document:sap:rfc:functions:ZGL_RMAWEB:ZGL_RMA_CRIA_RESERVARequest")
    @WebResult(name = "T_RETURN", targetNamespace = "")
    @RequestWrapper(localName = "ZGL_RMA_CRIA_RESERVA", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZGLRMACRIARESERVA")
    @ResponseWrapper(localName = "ZGL_RMA_CRIA_RESERVAResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZGLRMACRIARESERVAResponse")
    public ZGLSTABRESRETURN zglRMACRIARESERVA(
        @WebParam(name = "T_ITENS", targetNamespace = "")
        ZGLSTABRMARESERVA tITENS);

    /**
     * 
     * @param gsSAIDMERC
     * @return
     *     returns com.sap.document.sap.rfc.functions.ZGLSRMAMERCRETURN
     */
    @WebMethod(operationName = "ZGL_RMA_CRIA_SAIDA_MERCADORIA", action = "urn:sap-com:document:sap:rfc:functions:ZGL_RMAWEB:ZGL_RMA_CRIA_SAIDA_MERCADORIARequest")
    @WebResult(name = "GS_RETURN", targetNamespace = "")
    @RequestWrapper(localName = "ZGL_RMA_CRIA_SAIDA_MERCADORIA", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZGLRMACRIASAIDAMERCADORIA")
    @ResponseWrapper(localName = "ZGL_RMA_CRIA_SAIDA_MERCADORIAResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZGLRMACRIASAIDAMERCADORIAResponse")
    public ZGLSRMAMERCRETURN zglRMACRIASAIDAMERCADORIA(
        @WebParam(name = "GS_SAID_MERC", targetNamespace = "")
        ZGLSRMASAIDAMERCADORIA gsSAIDMERC);

    /**
     * 
     * @param input
     * @return
     *     returns com.sap.document.sap.rfc.functions.ZGLSRMAWEBSTOCKOUT
     */
    @WebMethod(operationName = "ZGL_RMA_BUSCA_ESTOQUE", action = "urn:sap-com:document:sap:rfc:functions:ZGL_RMAWEB:ZGL_RMA_BUSCA_ESTOQUERequest")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    @RequestWrapper(localName = "ZGL_RMA_BUSCA_ESTOQUE", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZGLRMABUSCAESTOQUE")
    @ResponseWrapper(localName = "ZGL_RMA_BUSCA_ESTOQUEResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZGLRMABUSCAESTOQUEResponse")
    public ZGLSRMAWEBSTOCKOUT zglRMABUSCAESTOQUE(
        @WebParam(name = "INPUT", targetNamespace = "")
        ZGLSRMAWEBSTOCKIN input);

}
